---
dist: bionic
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - COLLECTION_NAMESPACE: ericsysmin
    - COLLECTION_NAME: docker
  matrix:
    - MOLECULE_DISTRO=centos-7 MOLECULE_COMMAND=/usr/sbin/init
    - MOLECULE_DISTRO=centos-8 MOLECULE_COMMAND=/usr/sbin/init
    - MOLECULE_DISTRO=fedora-32 MOLECULE_COMMAND=/usr/sbin/init
    - MOLECULE_DISTRO=fedora-31 MOLECULE_COMMAND=/usr/lib/systemd/systemd
    - MOLECULE_DISTRO=fedora-30 MOLECULE_COMMAND=/usr/lib/systemd/systemd
    - MOLECULE_DISTRO=ubuntu-16.04 MOLECULE_COMMAND=/sbin/init
    - MOLECULE_DISTRO=ubuntu-18.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - MOLECULE_DISTRO=ubuntu-20.04 MOLECULE_COMMAND=/lib/systemd/systemd
    - MOLECULE_DISTRO=debian-9 MOLECULE_COMMAND=/lib/systemd/systemd
    - MOLECULE_DISTRO=debian-10 MOLECULE_COMMAND=/lib/systemd/systemd


install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  - molecule test
